load("@aspect_bazel_lib//:bzl_library.bzl", "bzl_library")

exports_files(
    ["extensions.bzl"],
    visibility = ["//visibility:public"],
)

bzl_library(
    name = "extensions",
    srcs = ["extensions.bzl"],
    visibility = ["//visibility:public"],
)
